### ISSUE TITLE
Graph numbers hidden when using OS dark mode + DSMR-reader light mode

### ISSUE THREAD

**Issue by leadenchopsticks** [dsmrreader/dsmr-reader#1602] opened 2022-03-21 19:29 UTC
### Description

After upgrading to 5.1 the GUI reverted to dark (probably due to my Mac settings). After manually changing to light theme, the numbers on the left and bottom of the graphs are not visible anymore.

### DSMR-reader version

5.1

### DSMR-reader platform

Native (e.g. manual installation)

**Comment by dennissiemensma** [comment] 2022-03-21 21:14
Would you be able to attach a screenshot of the issue?

**Comment by leadenchopsticks** [comment] 2022-03-22 07:27
Sure!

Working:

<img width="984" alt="Screenshot 2022-03-22 at 08 25 37" src="https://user-images.githubusercontent.com/70235789/159429167-bd42e8da-2528-471a-b615-783a697ac29a.png">

Not working:

<img width="1189" alt="Screenshot 2022-03-22 at 08 26 08" src="https://user-images.githubusercontent.com/70235789/159429077-a087e08e-176e-4465-a33d-f10c04ce6647.png">

**Comment by dennissiemensma** [comment] 2022-03-22 18:34
Unfortunately I'm unable to reproduce the issue in both Firefox or Chrome. 

Which browser are you using? Are you able to try another browser? Are there any errors on the Developer Tools' Console tab of your browser?

**Comment by leadenchopsticks** [comment] 2022-03-23 08:03
It happens in both Chrome and Safari. No errors in developer consoles. My default Mac setting is 'Dark'. 

Interestingly enough, when I change my Mac setting to 'Light' the numbers are showing up. So it seems to be an issue when manually selecting Light theme in DSMR reader in combination with Dark mode in OS.

**Comment by dennissiemensma** [comment] 2022-03-23 20:38
Great, I can now see the issue here as well. I've fixed the issue for v5.2

**Comment by dennissiemensma** [comment] 2022-03-23 20:40
Fixed in 900f8ab023475d34223e85473cd74f58ad3c0882 and will default to light mode in the future on error as well.

**Closed as completed by dennissiemensma** 2022-03-23 20:40 UTC
Labels: bug

**Comment by dennissiemensma** [comment] 2022-05-24 17:17
Net gereleased via [v5.2](https://dsmr-reader.readthedocs.io/en/v5/reference/changelog.html#v5-2-0-2022-05-24)
